module.exports = [
    {
        "id": "TN1",
        "transactionMemberID": "MN2",
        "transactionName": "Employment Pay",
        "transactionOrigin": "Amazon.com Inc.",
        "transactionType": "Debit",
        "transactionDate": "06-28-2024",
        "frequency": "bi-weekly",
        "amountInCents": 215000,
        "category": "Wages",
    },
    {
        "id": "TN2",
        "transactionMemberID": "MN1",
        "transactionName": "Electric Utility Payment",
        "transactionOrigin": "PSEG",
        "transactionType": "Credit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 25000,
        "category": "Home Expense",
    },
    {
        "id": "TN3",
        "transactionMemberID": "MN3",
        "transactionName": "Employment Pay",
        "transactionOrigin": "New York Department of Transportation",
        "transactionType": "Debit",
        "transactionDate": "06-15-2024",
        "frequency": "bi-monthly",
        "amountInCents": 171000,
        "category": "Wages",
    },
    {
        "id": "TN4",
        "transactionMemberID": "MN1",
        "transactionName": "Natural Gas Utility",
        "transactionOrigin": "Metro New York Gas",
        "transactionType": "Credit",
        "transactionDate": "06-22-2024",
        "frequency": "monthly",
        "amountInCents": 9829,
        "category": "Home Expense",
    },
    {
        "id": "TN5",
        "transactionMemberID": "MN1",
        "transactionName": "Rent",
        "transactionOrigin": "Skyview Lofts",
        "transactionType": "Credit",
        "transactionDate": "06-22-2024",
        "frequency": "monthly",
        "amountInCents": 9829,
        "category": "Home Expense",
    },
    {
        "id": "TN6",
        "transactionMemberID": "MN1",
        "transactionName": "Groceries",
        "transactionOrigin": "Whole Foods",
        "transactionType": "Credit",
        "transactionDate": "06-05-2024",
        "frequency": "weekly",
        "amountInCents": 15500,
        "category": "Living Expense",
    },
    {
        "id": "TN7",
        "transactionMemberID": "MN3",
        "transactionName": "Auto Insurance Payment",
        "transactionOrigin": "GEICO",
        "transactionType": "Credit",
        "transactionDate": "06-21-2024",
        "frequency": "monthly",
        "amountInCents": 28339,
        "category": "Auto Expense",
    },
    {
        "id": "TN8",
        "transactionMemberID": "MN2",
        "transactionName": "Auto Insurance Payment",
        "transactionOrigin": "Progressive",
        "transactionType": "Credit",
        "transactionDate": "06-14-2024",
        "frequency": "monthly",
        "amountInCents": 7629,
        "category": "Auto Expense",
    },
    {
        "id": "TN9",
        "transactionMemberID": "MN3",
        "transactionName": "Auto Lease Payment",
        "transactionOrigin": "Audi Financial Services",
        "transactionType": "Credit",
        "transactionDate": "06-17-2024",
        "frequency": "monthly",
        "amountInCents": 68738,
        "category": "Auto Expense",
    },
    {
        "id": "TN10",
        "transactionMemberID": "MN2",
        "transactionName": "Gym Membership Fee",
        "transactionOrigin": "L.A. Fitness",
        "transactionType": "Credit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 8500,
        "category": "Membership/Subscriptions",
    },   
]