module.exports = [
    {
        "id": 1,
        "transactionMemberID": 10001,
        "transactionName": "Employment Pay",
        "transactionOrigin": "Amazon.com Inc.",
        "transactionType": "Debit",
        "transactionDate": "06-28-2024",
        "frequency": "bi-weekly",
        "amountInCents": 215000,
        "category": "Wages",
    },
    {
        "id": 2,
        "transactionMemberID": 10000,
        "transactionName": "Electric Utility Payment",
        "transactionOrigin": "PSEG",
        "transactionType": "Credit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 25000,
        "category": "Home Expense",
    },
    {
        "id": 3,
        "transactionMemberID": 10002,
        "transactionName": "Employment Pay",
        "transactionOrigin": "New York Department of Transportation",
        "transactionType": "Debit",
        "transactionDate": "06-15-2024",
        "frequency": "bi-monthly",
        "amountInCents": 171000,
        "category": "Wages",
    },
    {
        "id": 4,
        "transactionMemberID": 10000,
        "transactionName": "Natural Gas Utility",
        "transactionOrigin": "Metro New York Gas",
        "transactionType": "Credit",
        "transactionDate": "06-22-2024",
        "frequency": "monthly",
        "amountInCents": 9829,
        "category": "Home Expense",
    },
    {
        "id": 5,
        "transactionMemberID": 10000,
        "transactionName": "Rent",
        "transactionOrigin": "Skyview Lofts",
        "transactionType": "Credit",
        "transactionDate": "06-22-2024",
        "frequency": "monthly",
        "amountInCents": 9829,
        "category": "Home Expense",
    },
    {
        "id": 5,
        "transactionMemberID": 10000,
        "transactionName": "Groceries",
        "transactionOrigin": "Whole Foods",
        "transactionType": "Credit",
        "transactionDate": "06-05-2024",
        "frequency": "weekly",
        "amountInCents": 15500,
        "category": "Living Expense",
    },
    {
        "id": 6,
        "transactionMemberID": 10002,
        "transactionName": "Auto Insurance Payment",
        "transactionOrigin": "GEICO",
        "transactionType": "Credit",
        "transactionDate": "06-21-2024",
        "frequency": "monthly",
        "amountInCents": 28339,
        "category": "Auto Expense",
    },
    {
        "id": 7,
        "transactionMemberID": 10001,
        "transactionName": "Auto Insurance Payment",
        "transactionOrigin": "Progressive",
        "transactionType": "Credit",
        "transactionDate": "06-14-2024",
        "frequency": "monthly",
        "amountInCents": 7629,
        "category": "Auto Expense",
    },
    {
        "id": 8,
        "transactionMemberID": 10002,
        "transactionName": "Auto Lease Payment",
        "transactionOrigin": "Audi Financial Services",
        "transactionType": "Credit",
        "transactionDate": "06-17-2024",
        "frequency": "monthly",
        "amountInCents": 68738,
        "category": "Auto Expense",
    },
    {
        "id": 9,
        "transactionMemberID": 10001,
        "transactionName": "Gym Membership Fee",
        "transactionOrigin": "L.A. Fitness",
        "transactionType": "Credit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 8500,
        "category": "Membership/Subscriptions",
    },   
]