module.exports = [
    {
        "id": "TN1",
        "transactionMemberID": "MN2",
        "transactionName": "Employment Pay",
        "transactionOrigin": "Amazon.com Inc.",
        "transactionType": "Credit",
        "transactionDate": "06-28-2024",
        "frequency": "bi-weekly",
        "amountInCents": 215000,
        "category": "Wages",
    },
    {
        "id": "TN2",
        "transactionMemberID": "MN1",
        "transactionName": "Electric Utility",
        "transactionOrigin": "PSEG",
        "transactionType": "Debit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 25000,
        "category": "Home",
    },
    {
        "id": "TN3",
        "transactionMemberID": "MN3",
        "transactionName": "Employment Pay",
        "transactionOrigin": "New York Department of Transportation",
        "transactionType": "Credit",
        "transactionDate": "06-15-2024",
        "frequency": "bi-monthly",
        "amountInCents": 171000,
        "category": "Wages",
    },
    {
        "id": "TN4",
        "transactionMemberID": "MN1",
        "transactionName": "Natural Gas Utility",
        "transactionOrigin": "Metro New York Gas",
        "transactionType": "Debit",
        "transactionDate": "06-22-2024",
        "frequency": "monthly",
        "amountInCents": 9829,
        "category": "Home",
    },
    {
        "id": "TN5",
        "transactionMemberID": "MN1",
        "transactionName": "Rent",
        "transactionOrigin": "Skyview Lofts",
        "transactionType": "Debit",
        "transactionDate": "06-22-2024",
        "frequency": "monthly",
        "amountInCents": 9829,
        "category": "Home",
    },
    {
        "id": "TN6",
        "transactionMemberID": "MN1",
        "transactionName": "Groceries",
        "transactionOrigin": "Whole Foods",
        "transactionType": "Debit",
        "transactionDate": "06-05-2024",
        "frequency": "weekly",
        "amountInCents": 15500,
        "category": "Living Expense",
    },
    {
        "id": "TN7",
        "transactionMemberID": "MN3",
        "transactionName": "Auto Insurance Premium",
        "transactionOrigin": "GEICO",
        "transactionType": "Debit",
        "transactionDate": "06-21-2024",
        "frequency": "monthly",
        "amountInCents": 28339,
        "category": "Auto",
    },
    {
        "id": "TN8",
        "transactionMemberID": "MN2",
        "transactionName": "Auto Insurance Payment",
        "transactionOrigin": "Progressive",
        "transactionType": "Debit",
        "transactionDate": "06-14-2024",
        "frequency": "monthly",
        "amountInCents": 7629,
        "category": "Auto",
    },
    {
        "id": "TN9",
        "transactionMemberID": "MN3",
        "transactionName": "Auto Lease",
        "transactionOrigin": "Audi Financial Services",
        "transactionType": "Debit",
        "transactionDate": "06-17-2024",
        "frequency": "monthly",
        "amountInCents": 68738,
        "category": "Auto",
    },
    {
        "id": "TN10",
        "transactionMemberID": "MN2",
        "transactionName": "Gym Membership Fee",
        "transactionOrigin": "L.A. Fitness",
        "transactionType": "Debit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 8500,
        "category": "Health/Wellness",
    },
    {
        "id": "TN11",
        "transactionMemberID": "MN2",
        "transactionName": "Dining Out",
        "transactionOrigin": "Pizza Hut",
        "transactionType": "Debit",
        "transactionDate": "06-02-2024",
        "frequency": "one-time",
        "amountInCents": 3000,
        "category": "Food"
      },
      {
        "id": "TN12",
        "transactionMemberID": "MN3",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-03-2024",
        "frequency": "one-time",
        "amountInCents": 4500,
        "category": "Shopping"
      },
      {
        "id": "TN13",
        "transactionMemberID": "MN1",
        "transactionName": "Water Utility",
        "transactionOrigin": "NYC Water",
        "transactionType": "Debit",
        "transactionDate": "06-04-2024",
        "frequency": "monthly",
        "amountInCents": 5052,
        "category": "Home"
      },
      {
        "id": "TN14",
        "transactionMemberID": "MN2",
        "transactionName": "Medical Checkup",
        "transactionOrigin": "City Clinic",
        "transactionType": "Debit",
        "transactionDate": "06-06-2024",
        "frequency": "one-time",
        "amountInCents": 20000,
        "category": "Health/Wellness"
      },
      {
        "id": "TN15",
        "transactionMemberID": "MN3",
        "transactionName": "Movie Tickets",
        "transactionOrigin": "AMC Theaters",
        "transactionType": "Debit",
        "transactionDate": "06-07-2024",
        "frequency": "one-time",
        "amountInCents": 3000,
        "category": "Entertainment"
      },
      {
        "id": "TN16",
        "transactionMemberID": "MN2",
        "transactionName": "Groceries",
        "transactionOrigin": "Trader Joe's",
        "transactionType": "Debit",
        "transactionDate": "06-08-2024",
        "frequency": "weekly",
        "amountInCents": 12500,
        "category": "Food"
      },
      {
        "id": "TN17",
        "transactionMemberID": "MN3",
        "transactionName": "Flight Booking",
        "transactionOrigin": "Delta Airlines",
        "transactionType": "Debit",
        "transactionDate": "06-09-2024",
        "frequency": "one-time",
        "amountInCents": 35000,
        "category": "Travel"
      },
      {
        "id": "TN18",
        "transactionMemberID": "MN1",
        "transactionName": "High-Speeed Internet Service",
        "transactionOrigin": "Verizon",
        "transactionType": "Debit",
        "transactionDate": "06-10-2024",
        "frequency": "monthly",
        "amountInCents": 4573,
        "category": "Home"
      },
      {
        "id": "TN19",
        "transactionMemberID": "MN2",
        "transactionName": "Gasoline",
        "transactionOrigin": "Shell",
        "transactionType": "Debit",
        "transactionDate": "06-11-2024",
        "frequency": "weekly",
        "amountInCents": 5000,
        "category": "Auto"
      },
      {
        "id": "TN20",
        "transactionMemberID": "MN3",
        "transactionName": "Car Repair",
        "transactionOrigin": "Midas",
        "transactionType": "Debit",
        "transactionDate": "06-12-2024",
        "frequency": "one-time",
        "amountInCents": 15000,
        "category": "Auto"
      },
      {
        "id": "TN21",
        "transactionMemberID": "MN1",
        "transactionName": "Television Cable Service",
        "transactionOrigin": "Optimum",
        "transactionType": "Debit",
        "transactionDate": "06-13-2024",
        "frequency": "monthly",
        "amountInCents": 6420,
        "category": "Home"
      },
      {
        "id": "TN22",
        "transactionMemberID": "MN2",
        "transactionName": "Birthday Gift From Grandma",
        "transactionOrigin": "Birthday Gift",
        "transactionType": "Credit",
        "transactionDate": "06-17-2024",
        "frequency": "one-time",
        "amountInCents": 10000,
        "category": "Gift"
      },
      {
        "id": "TN23",
        "transactionMemberID": "MN3",
        "transactionName": "Hotel Booking",
        "transactionOrigin": "Hilton",
        "transactionType": "Debit",
        "transactionDate": "06-16-2024",
        "frequency": "one-time",
        "amountInCents": 41957,
        "category": "Gift"
      },
      {
        "id": "TN24",
        "transactionMemberID": "MN1",
        "transactionName": "House Cleaning",
        "transactionOrigin": "Molly Maid",
        "transactionType": "Debit",
        "transactionDate": "06-17-2024",
        "frequency": "monthly",
        "amountInCents": 12000,
        "category": "Home"
      },
      {
        "id": "TN25",
        "transactionMemberID": "MN2",
        "transactionName": "Streaming Service Subscription",
        "transactionOrigin": "Netflix",
        "transactionType": "Debit",
        "transactionDate": "06-18-2024",
        "frequency": "monthly",
        "amountInCents": 1299,
        "category": "Entertainment"
      },
      {
        "id": "TN26",
        "transactionMemberID": "MN3",
        "transactionName": "Lunch",
        "transactionOrigin": "Subway",
        "transactionType": "Debit",
        "transactionDate": "06-19-2024",
        "frequency": "one-time",
        "amountInCents": 899,
        "category": "Food"
      },
      {
        "id": "TN27",
        "transactionMemberID": "MN1",
        "transactionName": "Laundry Service",
        "transactionOrigin": "Easy Street Laundry",
        "transactionType": "Debit",
        "transactionDate": "06-20-2024",
        "frequency": "weekly",
        "amountInCents": 1500,
        "category": "Home"
      },
      {
        "id": "TN28",
        "transactionMemberID": "MN2",
        "transactionName": "Concert Tickets",
        "transactionOrigin": "Ticketmaster",
        "transactionType": "Debit",
        "transactionDate": "06-21-2024",
        "frequency": "one-time",
        "amountInCents": 20000,
        "category": "Entertainment"
      },
      {
        "id": "TN29",
        "transactionMemberID": "MN3",
        "transactionName": "Dinner",
        "transactionOrigin": "Olive Garden",
        "transactionType": "Debit",
        "transactionDate": "06-22-2024",
        "frequency": "one-time",
        "amountInCents": 4500,
        "category": "Food"
      },
      {
        "id": "TN30",
        "transactionMemberID": "MN1",
        "transactionName": "Gardening Service",
        "transactionOrigin": "Green Thumb",
        "transactionType": "Debit",
        "transactionDate": "06-23-2024",
        "frequency": "monthly",
        "amountInCents": 3000,
        "category": "Home"
      },
      {
        "id": "TN31",
        "transactionMemberID": "MN2",
        "transactionName": "Pet Food",
        "transactionOrigin": "PetSmart",
        "transactionType": "Debit",
        "transactionDate": "06-24-2024",
        "frequency": "monthly",
        "amountInCents": 5000,
        "category": "Other"
      },
      {
        "id": "TN32",
        "transactionMemberID": "MN3",
        "transactionName": "Bank Transfer",
        "transactionOrigin": "Chase",
        "transactionType": "Credit",
        "transactionDate": "06-25-2024",
        "frequency": "one-time",
        "amountInCents": 340000,
        "category": "Bank Transfer"
      },
      {
        "id": "TN33",
        "transactionMemberID": "MN1",
        "transactionName": "Household Supplies",
        "transactionOrigin": "Walmart",
        "transactionType": "Debit",
        "transactionDate": "06-26-2024",
        "frequency": "monthly",
        "amountInCents": 7500,
        "category": "Home"
      },
      {
        "id": "TN34",
        "transactionMemberID": "MN2",
        "transactionName": "Sony 65 Inch 4K Ultra HD TV",
        "transactionOrigin": "Best Buy",
        "transactionType": "Debit",
        "transactionDate": "06-27-2024",
        "frequency": "one-time",
        "amountInCents": 68320,
        "category": "Shopping"
      },
      {
        "id": "TN35",
        "transactionMemberID": "MN3",
        "transactionName": "Car Wash",
        "transactionOrigin": "Walter's Car Wash & Detailing",
        "transactionType": "Debit",
        "transactionDate": "06-28-2024",
        "frequency": "weekly",
        "amountInCents": 1000,
        "category": "Auto"
      },
      {
        "id": "TN36",
        "transactionMemberID": "MN1",
        "transactionName": "TV Subscription",
        "transactionOrigin": "Hulu",
        "transactionType": "Debit",
        "transactionDate": "06-29-2024",
        "frequency": "monthly",
        "amountInCents": 599,
        "category": "Entertainment"
      },
      {
        "id": "TN37",
        "transactionMemberID": "MN2",
        "transactionName": "Starbuck's Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-30-2024",
        "frequency": "one-time",
        "amountInCents": 758,
        "category": "Food"
      },
      {
        "id": "TN38",
        "transactionMemberID": "MN3",
        "transactionName": "Window Treatments",
        "transactionOrigin": "Blinds 4 Less",
        "transactionType": "Debit",
        "transactionDate": "06-11-2024",
        "frequency": "one-time",
        "amountInCents": 30340,
        "category": "Home"
      },
      {
        "id": "TN39",
        "transactionMemberID": "MN2",
        "transactionName": "Interest Earnings",
        "transactionOrigin": "Bank of America",
        "transactionType": "Credit",
        "transactionDate": "06-15-2024",
        "frequency": "monthly",
        "amountInCents": 7,
        "category": "Interest"
      },
      {
        "id": "TN40",
        "transactionMemberID": "MN2",
        "transactionName": "Online Course",
        "transactionOrigin": "Udemy",
        "transactionType": "Debit",
        "transactionDate": "06-03-2024",
        "frequency": "one-time",
        "amountInCents": 2000,
        "category": "Other"
      },
      {
        "id": "TN41",
        "transactionMemberID": "MN3",
        "transactionName": "Retail Sale",
        "transactionOrigin": "Etsy",
        "transactionType": "Credit",
        "transactionDate": "06-15-2024",
        "frequency": "one-time",
        "amountInCents": 65190,
        "category": "Business"
      },
      {
        "id": "TN42",
        "transactionMemberID": "MN1",
        "transactionName": "Renter's Insurance Premium",
        "transactionOrigin": "Lemonade Insurance",
        "transactionType": "Debit",
        "transactionDate": "06-05-2024",
        "frequency": "monthly",
        "amountInCents": 1599,
        "category": "Auto"
      },
      {
        "id": "TN43",
        "transactionMemberID": "MN2",
        "transactionName": "Groceries",
        "transactionOrigin": "Trader Joe's",
        "transactionType": "Debit",
        "transactionDate": "06-06-2024",
        "frequency": "weekly",
        "amountInCents": 12500,
        "category": "Food"
      },
      {
        "id": "TN44",
        "transactionMemberID": "MN3",
        "transactionName": "Haircut",
        "transactionOrigin": "Barber Shop",
        "transactionType": "Debit",
        "transactionDate": "06-07-2024",
        "frequency": "monthly",
        "amountInCents": 2500,
        "category": "Health/Wellness"
      },
      {
        "id": "TN45",
        "transactionMemberID": "MN1",
        "transactionName": "Parking Access",
        "transactionOrigin": "Skyview Lofts",
        "transactionType": "Debit",
        "transactionDate": "06-01-2024",
        "frequency": "monthly",
        "amountInCents": 7500,
        "category": "Home"
      },
      {
        "id": "TN46",
        "transactionMemberID": "MN2",
        "transactionName": "Pet Food",
        "transactionOrigin": "PetSmart",
        "transactionType": "Debit",
        "transactionDate": "06-09-2024",
        "frequency": "monthly",
        "amountInCents": 5000,
        "category": "Other"
      },
      {
        "id": "TN47",
        "transactionMemberID": "MN3",
        "transactionName": "Bank Transfer",
        "transactionOrigin": "Zelle",
        "transactionType": "Debit",
        "transactionDate": "06-21-2024",
        "frequency": "one-time",
        "amountInCents": 11500,
        "category": "Other"
      },
      {
        "id": "TN48",
        "transactionMemberID": "MN1",
        "transactionName": "Household Supplies",
        "transactionOrigin": "Walmart",
        "transactionType": "Debit",
        "transactionDate": "06-11-2024",
        "frequency": "monthly",
        "amountInCents": 7500,
        "category": "Home"
      },
      {
        "id": "TN53",
        "transactionMemberID": "MN2",
        "transactionName": "Stock Dividend",
        "transactionOrigin": "Apple Inc.",
        "transactionType": "Credit",
        "transactionDate": "06-15-2024",
        "frequency": "quarterly",
        "amountInCents": 5000,
        "category": "Investment"
      },
      {
        "id": "TN54",
        "transactionMemberID": "MN3",
        "transactionName": "Bond Interest",
        "transactionOrigin": "US Treasury",
        "transactionType": "Credit",
        "transactionDate": "06-20-2024",
        "frequency": "semi-annually",
        "amountInCents": 7500,
        "category": "Investment"
      },
      {
        "id": "TN55",
        "transactionMemberID": "MN2",
        "transactionName": "Real Estate Investment",
        "transactionOrigin": "Realty Income Corp.",
        "transactionType": "Credit",
        "transactionDate": "06-25-2024",
        "frequency": "monthly",
        "amountInCents": 20000,
        "category": "Investment"
      },
      {
        "id": "TN56",
        "transactionMemberID": "MN2",
        "transactionName": "Uber Ride",
        "transactionOrigin": "Uber",
        "transactionType": "Debit",
        "transactionDate": "06-01-2024",
        "frequency": "one-time",
        "amountInCents": 1500,
        "category": "Travel"
      },
      {
        "id": "TN57",
        "transactionMemberID": "MN3",
        "transactionName": "Lyft Ride",
        "transactionOrigin": "Lyft",
        "transactionType": "Debit",
        "transactionDate": "06-03-2024",
        "frequency": "one-time",
        "amountInCents": 1800,
        "category": "Travel"
      },
      {
        "id": "TN58",
        "transactionMemberID": "MN2",
        "transactionName": "Uber Ride",
        "transactionOrigin": "Uber",
        "transactionType": "Debit",
        "transactionDate": "06-05-2024",
        "frequency": "one-time",
        "amountInCents": 3650,
        "category": "Travel"
      },
      {
        "id": "TN59",
        "transactionMemberID": "MN3",
        "transactionName": "Lyft Ride",
        "transactionOrigin": "Lyft",
        "transactionType": "Debit",
        "transactionDate": "06-07-2024",
        "frequency": "one-time",
        "amountInCents": 1750,
        "category": "Travel"
      },
      {
        "id": "TN60",
        "transactionMemberID": "MN2",
        "transactionName": "Uber Ride",
        "transactionOrigin": "Uber",
        "transactionType": "Debit",
        "transactionDate": "06-10-2024",
        "frequency": "one-time",
        "amountInCents": 1400,
        "category": "Travel"
      },
      {
        "id": "TN61",
        "transactionMemberID": "MN3",
        "transactionName": "Lyft Ride",
        "transactionOrigin": "Lyft",
        "transactionType": "Debit",
        "transactionDate": "06-12-2024",
        "frequency": "one-time",
        "amountInCents": 1900,
        "category": "Travel"
      },
      {
        "id": "TN62",
        "transactionMemberID": "MN2",
        "transactionName": "Uber Ride",
        "transactionOrigin": "Uber",
        "transactionType": "Debit",
        "transactionDate": "06-15-2024",
        "frequency": "one-time",
        "amountInCents": 1700,
        "category": "Travel"
      },
      {
        "id": "TN63",
        "transactionMemberID": "MN3",
        "transactionName": "Lyft Ride",
        "transactionOrigin": "Lyft",
        "transactionType": "Debit",
        "transactionDate": "06-17-2024",
        "frequency": "one-time",
        "amountInCents": 1650,
        "category": "Travel"
      },
      {
        "id": "TN64",
        "transactionMemberID": "MN2",
        "transactionName": "Uber Ride",
        "transactionOrigin": "Uber",
        "transactionType": "Debit",
        "transactionDate": "06-20-2024",
        "frequency": "one-time",
        "amountInCents": 1550,
        "category": "Travel"
      },
      {
        "id": "TN65",
        "transactionMemberID": "MN3",
        "transactionName": "Lyft Ride",
        "transactionOrigin": "Lyft",
        "transactionType": "Debit",
        "transactionDate": "06-22-2024",
        "frequency": "one-time",
        "amountInCents": 1800,
        "category": "Travel"
      },
      {
        "id": "TN66",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-01-2024",
        "frequency": "one-time",
        "amountInCents": 450,
        "category": "Food"
      },
      {
        "id": "TN67",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-03-2024",
        "frequency": "one-time",
        "amountInCents": 500,
        "category": "Food"
      },
      {
        "id": "TN68",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-05-2024",
        "frequency": "one-time",
        "amountInCents": 550,
        "category": "Food"
      },
      {
        "id": "TN69",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-07-2024",
        "frequency": "one-time",
        "amountInCents": 600,
        "category": "Food"
      },
      {
        "id": "TN70",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-09-2024",
        "frequency": "one-time",
        "amountInCents": 450,
        "category": "Food"
      },
      {
        "id": "TN71",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-11-2024",
        "frequency": "one-time",
        "amountInCents": 500,
        "category": "Food"
      },
      {
        "id": "TN72",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-13-2024",
        "frequency": "one-time",
        "amountInCents": 550,
        "category": "Food"
      },
      {
        "id": "TN73",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-15-2024",
        "frequency": "one-time",
        "amountInCents": 600,
        "category": "Food"
      },
      {
        "id": "TN74",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-17-2024",
        "frequency": "one-time",
        "amountInCents": 450,
        "category": "Food"
      },
      {
        "id": "TN75",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-19-2024",
        "frequency": "one-time",
        "amountInCents": 500,
        "category": "Food"
      },
      {
        "id": "TN76",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-21-2024",
        "frequency": "one-time",
        "amountInCents": 550,
        "category": "Food"
      },
      {
        "id": "TN77",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-23-2024",
        "frequency": "one-time",
        "amountInCents": 600,
        "category": "Food"
      },
      {
        "id": "TN78",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-25-2024",
        "frequency": "one-time",
        "amountInCents": 450,
        "category": "Food"
      },
      {
        "id": "TN79",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-27-2024",
        "frequency": "one-time",
        "amountInCents": 500,
        "category": "Food"
      },
      {
        "id": "TN80",
        "transactionMemberID": "MN2",
        "transactionName": "Coffee",
        "transactionOrigin": "Starbucks",
        "transactionType": "Debit",
        "transactionDate": "06-29-2024",
        "frequency": "one-time",
        "amountInCents": 550,
        "category": "Food"
      },
      {
        "id": "TN81",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-02-2024",
        "frequency": "one-time",
        "amountInCents": 300,
        "category": "Food"
      },
      {
        "id": "TN82",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-05-2024",
        "frequency": "one-time",
        "amountInCents": 350,
        "category": "Food"
      },
      {
        "id": "TN83",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-08-2024",
        "frequency": "one-time",
        "amountInCents": 400,
        "category": "Food"
      },
      {
        "id": "TN84",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-11-2024",
        "frequency": "one-time",
        "amountInCents": 350,
        "category": "Food"
      },
      {
        "id": "TN85",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-14-2024",
        "frequency": "one-time",
        "amountInCents": 300,
        "category": "Food"
      },
      {
        "id": "TN86",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-17-2024",
        "frequency": "one-time",
        "amountInCents": 400,
        "category": "Food"
      },
      {
        "id": "TN87",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-20-2024",
        "frequency": "one-time",
        "amountInCents": 350,
        "category": "Food"
      },
      {
        "id": "TN88",
        "transactionMemberID": "MN3",
        "transactionName": "Coffee",
        "transactionOrigin": "Dunkin' Donuts",
        "transactionType": "Debit",
        "transactionDate": "06-23-2024",
        "frequency": "one-time",
        "amountInCents": 300,
        "category": "Food"
      },
      {
        "id": "TN89",
        "transactionMemberID": "MN2",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-02-2024",
        "frequency": "one-time",
        "amountInCents": 3500,
        "category": "Shopping"
      },
      {
        "id": "TN90",
        "transactionMemberID": "MN3",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-04-2024",
        "frequency": "one-time",
        "amountInCents": 2200,
        "category": "Shopping"
      },
      {
        "id": "TN91",
        "transactionMemberID": "MN2",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-06-2024",
        "frequency": "one-time",
        "amountInCents": 4300,
        "category": "Shopping"
      },
      {
        "id": "TN92",
        "transactionMemberID": "MN3",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-08-2024",
        "frequency": "one-time",
        "amountInCents": 1800,
        "category": "Shopping"
      },
      {
        "id": "TN93",
        "transactionMemberID": "MN2",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-10-2024",
        "frequency": "one-time",
        "amountInCents": 3900,
        "category": "Shopping"
      },
      {
        "id": "TN94",
        "transactionMemberID": "MN3",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-12-2024",
        "frequency": "one-time",
        "amountInCents": 2700,
        "category": "Shopping"
      },
      {
        "id": "TN95",
        "transactionMemberID": "MN2",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-14-2024",
        "frequency": "one-time",
        "amountInCents": 4100,
        "category": "Shopping"
      },
      {
        "id": "TN96",
        "transactionMemberID": "MN3",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-16-2024",
        "frequency": "one-time",
        "amountInCents": 2400,
        "category": "Shopping"
      },
      {
        "id": "TN97",
        "transactionMemberID": "MN2",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-18-2024",
        "frequency": "one-time",
        "amountInCents": 3500,
        "category": "Shopping"
      },
      {
        "id": "TN98",
        "transactionMemberID": "MN3",
        "transactionName": "Amazon Order",
        "transactionOrigin": "Amazon",
        "transactionType": "Debit",
        "transactionDate": "06-20-2024",
        "frequency": "one-time",
        "amountInCents": 3300,
        "category": "Shopping"
      },
      {
        "id": "TN99",
        "transactionMemberID": "MN2",
        "transactionName": "Pet Insurance",
        "transactionOrigin": "PetSmart",
        "transactionType": "Debit",
        "transactionDate": "06-15-2024",
        "frequency": "monthly",
        "amountInCents": 2220,
        "category": "Other"
      },
      {
        "id": "TN100",
        "transactionMemberID": "MN3",
        "transactionName": "Cellular Service",
        "transactionOrigin": "AT&T",
        "transactionType": "Debit",
        "transactionDate": "06-25-2024",
        "frequency": "one-time",
        "amountInCents": 18735,
        "category": "Home"
      } 
]